### ISSUE TITLE
환경에 맞는 mysql server가 생성되어야 합니다.

### ISSUE THREAD

**Issue by parkgang** [belf-kr/infrastructure-as-code#2]
`qa`, `prod` 환경에 맞는 mysql:5.7.16 server가 제공되어야합니다.

1. qa
   1. 인스턴스 개수의 한계로 deployment object 형태로 단일 서버로 구현됩니다.
   2. Azure Files Storage으로 저장합니다.
1. prod
   1. mysql replicated 으로 구현됩니다. `master` 와 `slaves` 가 있어야합니다.

**Comment by jp3pe** [comment]
@parkgang mysql:5.7.16 버전입니다(엄격, 근엄, 진지)

**Comment by parkgang** [comment]
> @parkgang mysql:5.7.16 버전입니다(엄격, 근엄, 진지)

@JP3Pe 수정했습니다.
